name: mafioso
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any
  easy_localization: ^3.0.4
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.7.0
  
  # Navigation
  # Using onGenerateRoute instead of go_router
  
  # HTTP & API
  dio: ^5.7.0
  
  # Animations
  flutter_animate: ^4.5.0
  
  # Audio
  audioplayers: ^6.1.0
  
  # Fonts
  google_fonts: ^6.2.1
  
  # Connectivity
  connectivity_plus: ^6.1.0
  
  # Local Storage
  shared_preferences: ^2.3.3

  # Environment Variables
  flutter_dotenv: ^5.1.0
  
  # Responsive Design
  flutter_screenutil: ^5.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4

  custom_lint: ^0.7.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  bloc_test: ^9.1.6

flutter_launcher_icons:
  android: true
  image_path_android: assets/images/logo.png
  adaptive_icon_background: "#0D0D0D"
  adaptive_icon_foreground: assets/images/logo.png

flutter_native_splash:
  android: true
  ios: false
  web: false

  color: "#0D0D0D"
  image: assets/images/logo.png

  android_12:
    color: "#0D0D0D"
    image: assets/images/logo.png  


flutter:
  uses-material-design: true
  
  assets:
    - assets/audio/
    - assets/images/
    - assets/data/
    - assets/data/stories_offline_en.json
    - assets/translations/
    - .env
